### ISSUE TITLE
React 18

### ISSUE THREAD

**Issue by BenzoMatrix** [kyr0/nes-ui-react#2]
Hey guys, I noticed you had attempted a merge 2 months ago to update the peer dependencies to react 18 but it failed the pipeline. I was just looking at this package today to use in my app and it threw the error on install. Wasn't sure if you noticed it.

**Comment by kyr0** [comment]
Hey @BenzoMatrix - sorry for the delay. You're right. I now took a few minutes to bump the whole project to 2024. The [docs site](https://github.com/kyr0/nes-ui-react/tree/main/docs) uses React 18 and Next 14 as a demo now. The library uses v18 as well. It all seems safe and sound. Could you please verify that version `0.3.0` is working fine for you? And if not, please screenshot the error message? Thank you!

**Comment by kyr0** [comment]
Closing, as this should be working :)

**Comment by BenzoMatrix** [comment]
Works for me! Thank you :)
